services:
  db_postgres:
    image: postgres:13
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: jack4385pno3485v3c45p8
      POSTGRES_PASSWORD: vwsjlter8v7inevr76thivwen7rtyv
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network

  backend_api:
    build: .
    container_name: backend_api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - db_postgres
    networks:
      - main_network

volumes:
  postgres_data:
    driver: local

networks:
  main_network:
    driver: bridge