# Generated by Django 5.1.2 on 2024-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('tg_acc', models.CharField(blank=True, max_length=255, null=True)),
                ('chatid', models.CharField(max_length=255, unique=True)),
                ('created_dttm', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
                ('meeting_count', models.IntegerField(default=0)),
                ('last_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('last_balance_update', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
