# Generated by Django 5.1.2 on 2024-10-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utm_send_transcription',
            field=models.BooleanField(default=False, verbose_name='Отправлять транскрибацию'),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_type_of_report',
            field=models.IntegerField(default=0, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chatid',
            field=models.CharField(max_length=255, unique=True, verbose_name='chatid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий utm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_balance_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего начисления баланса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней встречи'),
        ),
        migrations.AlterField(
            model_name='user',
            name='meeting_count',
            field=models.IntegerField(default=0, verbose_name='Количество встреч'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_acc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram аккаунт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название кампании utm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор объявления utm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип трафика utm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник кампании utm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='utm_term',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевое слово'),
        ),
    ]
